import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
cfg = json.load(open(os.path.join(ROOT, "data/site.config.json"), encoding="utf-8"))
tools = json.load(open(os.path.join(ROOT, "data/tools.json"), encoding="utf-8"))
cats = json.load(open(os.path.join(ROOT, "data/categories.json"), encoding="utf-8"))

def build_tools_data_js():
    """Regenerates the embedded search index from the JSON registries on every build,
    so data/tools.json remains the single source of truth (fixes a real bug where this
    file went stale after tools were added directly to the registry without re-running
    this step)."""
    js = "// AUTO-GENERATED by build.py from data/tools.json + data/categories.json. Do not edit by hand.\n"
    js += "const TOOLS = " + json.dumps(tools, indent=2) + ";\n"
    js += "const CATEGORIES = " + json.dumps(cats, indent=2) + ";\n"
    open(os.path.join(ROOT, "assets/js/tools-data.js"), "w", encoding="utf-8").write(js)

BRAND = cfg["brandName"]
URL = cfg["url"]

# ---------------- Icon system ----------------
# Hand-authored, lightweight inline SVGs in a Lucide/Feather-style outline language
# (stroke="currentColor", 1.8px stroke, round caps). Zero network requests, zero JS,
# inherits color via currentColor so it works with hover states and (future) dark mode.
def icon(name, size=22):
    paths = {
        "document": '<path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/><path d="M9 13h6M9 17h6"/>',
        "image": '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="1.7"/><path d="M21 16l-5.5-5.5L6 20"/>',
        "compress": '<path d="M8 3v4a1 1 0 0 1-1 1H3M16 3v4a1 1 0 0 0 1 1h4M8 21v-4a1 1 0 0 0-1-1H3M16 21v-4a1 1 0 0 1 1-1h4"/>',
        "split": '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16" stroke-dasharray="3 3"/>',
        "merge": '<path d="M6 3v7a4 4 0 0 0 4 4h4M6 3H3m3 0h3M18 3v7M18 3h3m-3 0h-3"/><path d="M14 14l4 4-4 4"/>',
        "word": '<path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/><path d="M8 13l1.3 6L11 14l1.7 5L14 13"/>',
        "ppt": '<path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/><rect x="8.5" y="12" width="3" height="6" rx=".5"/><path d="M11.5 12h2a2 2 0 1 1 0 4h-2"/>',
        "excel": '<path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/><path d="M8.5 12.5l5 6M13.5 12.5l-5 6"/>',
        "upload-cloud": '<path d="M7 18a4 4 0 0 1-1-7.9A5.5 5.5 0 0 1 16.9 8H17a4 4 0 0 1 1 7.9"/><path d="M12 12v8m0-8l-3 3m3-3l3 3"/>',
        "download": '<path d="M12 3v12m0 0l-4-4m4 4l4-4"/><path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2"/>',
        "check-circle": '<circle cx="12" cy="12" r="9"/><path d="M8.5 12.5l2.3 2.3L16 10"/>',
        "search": '<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',
        "calculator": '<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h.01M12 11h.01M16 11h.01M8 15h.01M12 15h.01M16 15h.01M8 19h.01M12 19h.01M16 19h.01"/>',
        "wallet": '<path d="M3 7a2 2 0 0 1 2-2h13a1 1 0 0 1 1 1v3H5a2 2 0 0 1-2-2z"/><path d="M3 7v11a2 2 0 0 0 2 2h14a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H5"/><circle cx="16" cy="14" r="1.3"/>',
        "cap": '<path d="M12 4L2 9l10 5 8-4v6"/><path d="M6 11.5V16c0 1.5 3 3 6 3s6-1.5 6-3v-4.5"/>',
        "briefcase": '<rect x="3" y="7" width="18" height="12" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18"/>',
        "ruler": '<path d="M3 7h18v10H3z"/><path d="M7 7v3M11 7v5M15 7v3M19 7v5"/>',
        "sparkle": '<path d="M12 3l1.8 4.8L18.5 9l-4.7 1.8L12 15l-1.8-4.2L5.5 9l4.7-1.2z"/><path d="M19 15l.8 2 2 .8-2 .8-.8 2-.8-2-2-.8 2-.8z"/>',
        "everyday": '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
        "qr": '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 14h3v3h-3zM19 14h2M14 19h2M19 19h2"/>',
        "converter": '<path d="M7 7h11l-3-3M17 17H6l3 3"/>',
        "resume": '<path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/><circle cx="11" cy="12.5" r="1.8"/><path d="M8.3 17c.5-1.6 1.8-2.5 3.2-2.5s2.7.9 3.2 2.5"/>',
    }
    p = paths.get(name, paths["document"])
    return ('<svg width="%d" height="%d" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">%s</svg>') % (size, size, p)

CATEGORY_ICON = {
    "student": "cap", "finance": "wallet", "pdf": "document", "ai": "sparkle",
    "calculators": "calculator", "converters": "converter", "career": "briefcase", "everyday": "everyday",
}
TOOL_ICON_OVERRIDE = {
    "pdf-to-jpg": "image", "pdf-to-png": "image", "jpg-to-pdf": "document",
    "compress-pdf": "compress", "split-pdf": "split", "merge-pdf": "merge",
    "pdf-to-word": "word", "pdf-to-ppt": "ppt", "pdf-to-excel": "excel",
    "qr-code-generator": "qr", "resume-builder": "resume", "unit-converter": "converter",
}
def tool_icon_name(t):
    return TOOL_ICON_OVERRIDE.get(t["slug"], CATEGORY_ICON.get(t["category"], "document"))

tool_by_slug = {t["slug"]: t for t in tools}
cat_by_slug = {c["slug"]: c for c in cats}
tools_by_cat = {}
for t in tools:
    tools_by_cat.setdefault(t["category"], []).append(t)

NAV_ITEMS = [
    ("/tools/student.html" if False else "/categories/student.html", "Student"),
    ("/categories/finance.html", "Finance"),
    ("/categories/pdf.html", "PDF"),
    ("/categories/career.html", "Career"),
    ("/tools.html", "All Tools"),
]

def header(active_path="/"):
    links = "".join(
        '<li><a href="%s">%s</a></li>' % (href, label) for href, label in NAV_ITEMS
    )
    return """
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header" id="site-header">
  <div class="container row">
    <a class="brand" href="/">
      <span class="brand-mark" aria-hidden="true">%s</span>%s
    </a>
    <nav aria-label="Primary">
      <ul class="nav-links">%s</ul>
    </nav>
    <div class="nav-right">
      <a class="nav-search-btn" href="/tools.html" aria-label="Search tools">%s</a>
      <button class="nav-toggle" aria-label="Toggle menu" aria-expanded="false">
        <span class="nav-toggle-bar"></span><span class="nav-toggle-bar"></span><span class="nav-toggle-bar"></span>
      </button>
    </div>
  </div>
</header>
""" % (icon("sparkle", 18), BRAND, links, icon("search", 18))

def footer():
    return """
<footer class="site-footer">
  <div class="container">
    <div class="footer-grid">
      <div>
        <a class="brand" href="/" style="margin-bottom:10px"><span class="brand-mark" aria-hidden="true">%s</span>%s</a>
        <p style="color:var(--ink-soft);font-size:.9rem;max-width:320px">%s</p>
      </div>
      <div>
        <h4>Categories</h4>
        <ul>
          %s
        </ul>
      </div>
      <div>
        <h4>Popular Tools</h4>
        <ul>
          %s
        </ul>
      </div>
      <div>
        <h4>Company</h4>
        <ul>
          <li><a href="/about.html">About</a></li>
          <li><a href="/contact.html">Contact</a></li>
          <li><a href="/privacy-policy.html">Privacy Policy</a></li>
          <li><a href="/terms.html">Terms of Use</a></li>
          <li><a href="/disclaimer.html">Disclaimer</a></li>
        </ul>
      </div>
    </div>
    <div class="footer-bottom">
      <span>&copy; <span id="year"></span> %s. %s</span>
      <span>Contact: <a href="mailto:%s">%s</a></span>
    </div>
  </div>
</footer>
<script>document.getElementById('year').textContent = new Date().getFullYear();</script>
""" % (
        icon("sparkle", 16), BRAND,
        cfg["description"],
        "".join('<li><a href="/categories/%s.html">%s</a></li>' % (c["slug"], c["name"]) for c in cats),
        "".join('<li><a href="/tools/%s.html">%s</a></li>' % (t["slug"], t["name"]) for t in tools[:6]),
        BRAND,
        cfg["footerNote"],
        cfg["contactEmail"],
        cfg["contactEmail"],
    )

def page(title, description, canonical, body, extra_head="", body_attrs="", schema=""):
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s</title>
<meta name="description" content="%s">
<link rel="canonical" href="%s">
<meta property="og:title" content="%s">
<meta property="og:description" content="%s">
<meta property="og:type" content="website">
<meta property="og:url" content="%s">
<meta property="og:site_name" content="%s">
<meta property="og:image" content="%s/assets/icons/icon-512.png">
<meta property="og:locale" content="en_IN">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="%s">
<meta name="twitter:description" content="%s">
<meta name="twitter:image" content="%s/assets/icons/icon-512.png">
<meta name="theme-color" content="%s">
<link rel="manifest" href="/manifest.json">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/icon-32.png">
<link rel="apple-touch-icon" href="/assets/icons/icon-180.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap">
<link rel="stylesheet" href="/assets/css/style.css">
<script src="/assets/js/tools-data.js"></script>
<script src="/assets/js/site.js"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7811625552429496"
     crossorigin="anonymous"></script>
%s
</head>
<body %s>
%s
<main id="main">
%s
</main>
%s
</body>
</html>""" % (
        title, description, canonical, title, description, canonical, BRAND, URL,
        title, description, URL, cfg["themeColor"], extra_head + schema, body_attrs,
        header(), body, footer()
    )

os.makedirs(os.path.join(ROOT, "tools"), exist_ok=True)
os.makedirs(os.path.join(ROOT, "categories"), exist_ok=True)

POPULAR_SLUGS = ["sgpa-calculator","emi-calculator","attendance-calculator","age-calculator",
                  "gst-calculator","bmi-calculator","unit-converter","qr-code-generator",
                  "resume-builder","jpg-to-pdf","sip-calculator","percentage-calculator"]

def tool_card(t):
    return """<a class="tool-card" href="/tools/%s.html">
      <span class="tool-card-icon">%s</span>
      <span class="cat-tag">%s</span>
      <h3>%s</h3>
      <p>%s</p>
    </a>""" % (t["slug"], icon(tool_icon_name(t)), cat_by_slug[t["category"]]["name"], t["name"], t["short"])

def cat_card(c):
    n = len(tools_by_cat.get(c["slug"], []))
    return """<a class="cat-card" href="/categories/%s.html">
      <span class="cat-card-icon">%s</span>
      <h3>%s</h3>
      <p>%s &middot; %d tool%s</p>
    </a>""" % (c["slug"], icon(CATEGORY_ICON.get(c["slug"], "document"), 24), c["name"], c["description"], n, "" if n == 1 else "s")

# ---------------- Homepage ----------------
def build_homepage():
    popular = [tool_by_slug[s] for s in POPULAR_SLUGS if s in tool_by_slug]
    faqs = [
        ("Is %s really free to use?" % BRAND, "Yes. Every tool on %s is free, with no signup required for core tools. Some AI-assisted tools may have a daily usage limit to keep the service sustainable." % BRAND),
        ("Do I need to create an account?", "No. Calculators, converters and document tools work without any account. We only ask for an account if we add optional premium features in the future."),
        ("Is my data safe when I use PDF or image tools?", "Wherever practical, files are processed directly in your browser and never uploaded to a server. Each tool page tells you clearly how your data is handled."),
        ("Can I use %s on my phone?" % BRAND, "Yes, every tool is designed mobile-first and works on any modern phone or desktop browser."),
    ]
    body = """
<section class="hero">
  <div class="hero-bg" aria-hidden="true"></div>
  <div class="container">
    <span class="hero-badge animate-in">%s Free &middot; No signup &middot; Works on any device</span>
    <h1 class="animate-in">Free Online Tools for Everyday Tasks</h1>
    <p class="sub animate-in">PDF tools, calculators, converters and productivity tools &mdash; all in one place.</p>
    <div class="search-box animate-in">
      <span class="search-icon" aria-hidden="true">%s</span>
      <label for="home-search" class="visually-hidden">Search for a tool</label>
      <input id="home-search" type="text" placeholder="Search tools... e.g. PDF to JPG, EMI Calculator" autocomplete="off">
      <div id="home-search-results" class="search-results" style="display:none"></div>
    </div>
    <p class="search-hint">Try: SGPA Calculator, EMI Calculator, QR Code Generator&hellip;</p>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-head"><h2>Popular Tools</h2><a href="/tools.html">View all tools &rarr;</a></div>
    <div class="grid grid-4">
      %s
    </div>
  </div>
</section>

<section class="pdf-spotlight">
  <div class="container">
    <div class="section-head">
      <div>
        <h2>Popular PDF Tools</h2>
        <p class="section-sub">Convert, compress, split and manage your PDFs instantly.</p>
      </div>
      <a href="/categories/pdf.html">View all PDF tools &rarr;</a>
    </div>
    <div class="grid grid-4">
      %s
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-head"><h2>Categories</h2></div>
    <div class="grid grid-4">
      %s
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-head"><h2>Why use %s?</h2></div>
    <div class="grid grid-3">
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>Free</h3><p>No cost, no hidden charges on core tools.</p></div>
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>Fast</h3><p>Lightweight pages built for slow connections and cheap phones.</p></div>
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>No unnecessary signup</h3><p>Use most tools instantly &mdash; no account required.</p></div>
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>Privacy-focused</h3><p>Document tools process files locally wherever possible.</p></div>
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>Mobile-friendly</h3><p>Designed mobile-first for the way India actually browses.</p></div>
      <div class="cat-card"><span class="cat-card-icon">%s</span><h3>Easy to use</h3><p>Clear layouts, plain-language explanations, no clutter.</p></div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-head"><h2>Popular searches</h2></div>
    <p>
      %s
    </p>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-head"><h2>Frequently asked questions</h2></div>
    <div class="faq">
      %s
    </div>
  </div>
</section>

<script>window.ToolNagri && window.ToolNagri.initSearch && window.ToolNagri.initSearch('home-search','home-search-results');</script>
"""
    schema = """<script type="application/ld+json">
%s
</script>""" % json.dumps({
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": BRAND,
        "url": URL,
        "potentialAction": {"@type": "SearchAction", "target": URL + "/tools.html?q={search_term_string}", "query-input": "required name=search_term_string"}
    })
    html = page(
        title="%s &mdash; Free Online Tools for Everyday Problems" % BRAND,
        description=cfg["description"],
        canonical=URL + "/",
        body=body % (
            icon("check-circle", 14),
            icon("search", 20),
            "\n".join(tool_card(t) for t in popular),
            "\n".join(tool_card(t) for t in tools_by_cat.get("pdf", [])[:8]),
            "\n".join(cat_card(c) for c in cats),
            BRAND,
            icon("check-circle"), icon("sparkle"), icon("everyday"), icon("document"), icon("everyday"), icon("check-circle"),
            " &middot; ".join('<a href="/tools/%s.html">%s</a>' % (t["slug"], t["name"]) for t in tools),
            "\n".join('<details><summary>%s</summary><p>%s</p></details>' % f for f in faqs),
        ),
        schema=schema,
    )
    open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8").write(html)

# ---------------- All tools page ----------------
def build_all_tools_page():
    body = """
<div class="container" style="padding-top:32px">
  <h1>All Tools</h1>
  <p style="color:var(--ink-soft);max-width:640px">Browse every tool on %s, organised by category. New tools are added regularly.</p>
  <div class="search-box" style="margin:20px 0 30px">
    <label for="all-search" class="visually-hidden">Search for a tool</label>
    <input id="all-search" type="text" placeholder="Search for a tool..." autocomplete="off">
    <div id="all-search-results" class="search-results" style="display:none"></div>
  </div>
  %s
</div>
<script>window.ToolNagri && window.ToolNagri.initSearch && window.ToolNagri.initSearch('all-search','all-search-results');</script>
""" % (
        BRAND,
        "\n".join(
            '<section><div class="section-head"><h2>%s</h2><a href="/categories/%s.html">View category &rarr;</a></div><div class="grid grid-4">%s</div></section>' % (
                c["name"], c["slug"], "\n".join(tool_card(t) for t in tools_by_cat.get(c["slug"], []))
            )
            for c in cats if tools_by_cat.get(c["slug"])
        ),
    )
    html = page(
        title="All Free Online Tools | %s" % BRAND,
        description="Browse the full list of free calculators, converters, PDF tools and career tools on %s." % BRAND,
        canonical=URL + "/tools.html",
        body=body,
    )
    open(os.path.join(ROOT, "tools.html"), "w", encoding="utf-8").write(html)

# ---------------- Category pages ----------------
def build_category_pages():
    for c in cats:
        clist = tools_by_cat.get(c["slug"], [])
        if not clist:
            continue
        body = """
<div class="container" style="padding-top:24px">
  <p class="breadcrumb"><a href="/">Home</a> / <a href="/tools.html">Tools</a> / %s</p>
  <h1>%s</h1>
  <p style="color:var(--ink-soft);max-width:640px">%s</p>
  <div class="grid grid-4" style="margin-top:24px">
    %s
  </div>
  <section>
    <div class="section-head"><h2>Other categories</h2></div>
    <div class="grid grid-4">
      %s
    </div>
  </section>
</div>
""" % (
            c["name"], c["name"], c["description"],
            "\n".join(tool_card(t) for t in clist),
            "\n".join(cat_card(o) for o in cats if o["slug"] != c["slug"] and tools_by_cat.get(o["slug"])),
        )
        html = page(
            title="%s | %s" % (c["name"], BRAND),
            description=c["description"],
            canonical="%s/categories/%s.html" % (URL, c["slug"]),
            body=body,
        )
        open(os.path.join(ROOT, "categories", c["slug"] + ".html"), "w", encoding="utf-8").write(html)

# ---------------- Legal / trust pages ----------------
def build_static_pages():
    pages = {
        "about.html": ("About Us", "About %s" % BRAND, """
<h1>About %s</h1>
<p>%s is a free online utility hub built for Indian students and professionals. We started with one idea:
everyday calculations and document tasks &mdash; SGPA, EMI, attendance, PDF conversion &mdash; shouldn't require an app download,
an account, or a fee.</p>
<h2>What we believe</h2>
<ul>
  <li>Tools should be free and fast, with no unnecessary signup.</li>
  <li>Your documents and personal data are yours &mdash; we process what we can directly in your browser.</li>
  <li>Good tools explain themselves. Every calculator on this site explains how the number was calculated.</li>
</ul>
<p>We are a small, independent project. If something is broken or missing, <a href="/contact.html">let us know</a>.</p>
""" % (BRAND, BRAND)),
        "contact.html": ("Contact Us", "Contact %s" % BRAND, """
<h1>Contact Us</h1>
<p>Questions, bug reports or tool requests &mdash; we read every message.</p>
<p>Email: <a href="mailto:%s">%s</a></p>
<p>We aim to respond within a few business days. For fastest resolution, tell us which tool you were using, what device/browser, and what you expected to happen.</p>
""" % (cfg["contactEmail"], cfg["contactEmail"])),
        "privacy-policy.html": ("Privacy Policy", "Privacy Policy | %s" % BRAND, """
<h1>Privacy Policy</h1>
<p><em>Last updated: 2026.</em></p>
<h2>What we collect</h2>
<p>We do not require an account to use core tools, so we do not collect names, emails or personal identifiers for basic tool usage.
If you use the contact form or email us, we store your message and email address only to reply to you.</p>
<h2>Document and file tools</h2>
<p>Tools such as JPG to PDF, Merge PDF and Image Compressor process files directly in your browser using JavaScript.
These files are never uploaded to our servers. Nothing you process through these tools is stored, logged or seen by us.</p>
<h2>Resume Builder</h2>
<p>Resume data you enter is stored only in your browser's local storage on your own device. It is not sent to our servers unless you explicitly choose a feature that requires it (none do, in the current version).</p>
<h2>Analytics</h2>
<p>We may use privacy-conscious analytics (such as Google Analytics) to understand which tools are useful and to fix bugs.
Analytics tracks anonymous usage events (e.g. "tool opened") and does not receive the content of your documents, resumes or calculations.</p>
<h2>Cookies</h2>
<p>We use minimal cookies/local storage strictly for functionality, such as remembering your recently used and favourite tools.</p>
<h2>Third-party links</h2>
<p>Some pages may link to third-party resources. We are not responsible for the privacy practices of external sites.</p>
<h2>Your rights</h2>
<p>Since we store very little personal data, most requests can be resolved by simply clearing your browser's local storage. For anything else, contact us at %s.</p>
""" % cfg["contactEmail"]),
        "terms.html": ("Terms of Use", "Terms of Use | %s" % BRAND, """
<h1>Terms of Use</h1>
<p>By using %s, you agree to the following:</p>
<h2>Use of tools</h2>
<p>Tools are provided "as is" for informational and educational purposes. Calculators (financial, academic, health) provide estimates
based on the inputs you provide and standard formulas &mdash; they are not professional advice.</p>
<h2>No warranty</h2>
<p>We make reasonable efforts to keep calculations accurate and the site available, but we do not guarantee uninterrupted access or
that results will be error-free. Always verify important calculations independently.</p>
<h2>Acceptable use</h2>
<p>Do not use this site to upload or process unlawful content, or to attempt to disrupt or reverse-engineer the service.</p>
<h2>Changes</h2>
<p>We may update these terms as the site evolves. Continued use of the site means you accept the current terms.</p>
""" % BRAND),
        "disclaimer.html": ("Disclaimer", "Disclaimer | %s" % BRAND, """
<h1>Disclaimer</h1>
<h2>Financial tools</h2>
<p>EMI, SIP, GST and other finance calculators on %s are educational tools based on standard formulas and the numbers you enter.
They do not constitute financial, investment or tax advice. Actual bank/lender terms, fund performance and tax rules may differ.
Please consult a qualified financial advisor or the relevant institution before making financial decisions.</p>
<h2>Health tools</h2>
<p>BMI and similar health calculators provide general estimates only and are not medical advice or a diagnosis.
Please consult a qualified healthcare professional for medical guidance.</p>
<h2>AI-assisted tools</h2>
<p>Where AI-generated suggestions are offered (e.g. resume or text tools), review all AI output carefully before use.
AI suggestions may be incomplete, generic, or occasionally incorrect.</p>
<h2>Academic tools</h2>
<p>SGPA/CGPA/attendance calculators follow commonly used formulas but individual institutions may apply different rules.
Always confirm final figures against your institution's official grading policy.</p>
""" % BRAND),
    }
    for fname, (title, seo_title, content) in pages.items():
        body = '<div class="container content-block" style="padding-top:24px">%s</div>' % content
        html = page(
            title=seo_title, description=title + " for " + BRAND,
            canonical="%s/%s" % (URL, fname), body=body,
        )
        open(os.path.join(ROOT, fname), "w", encoding="utf-8").write(html)

def build_404():
    body = """
<div class="container" style="padding:80px 0;text-align:center">
  <h1>404 &mdash; Page not found</h1>
  <p style="color:var(--ink-soft);max-width:480px;margin:0 auto 20px">The page you're looking for doesn't exist or may have moved.</p>
  <a class="btn btn-primary" href="/">Go to homepage</a>
  <a class="btn btn-secondary" href="/tools.html">Browse all tools</a>
</div>
"""
    html = page(title="Page Not Found | %s" % BRAND, description="Page not found.", canonical=URL + "/404.html", body=body)
    open(os.path.join(ROOT, "404.html"), "w", encoding="utf-8").write(html)

def build_sitemap():
    urls = [URL + "/", URL + "/tools.html", URL + "/about.html", URL + "/contact.html",
            URL + "/privacy-policy.html", URL + "/terms.html", URL + "/disclaimer.html"]
    urls += [URL + "/categories/%s.html" % c["slug"] for c in cats if tools_by_cat.get(c["slug"])]
    urls += [URL + "/tools/%s.html" % t["slug"] for t in tools]
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for u in urls:
        xml += "  <url><loc>%s</loc></url>\n" % u
    xml += "</urlset>\n"
    open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(xml)

def build_robots():
    txt = "User-agent: *\nAllow: /\nSitemap: %s/sitemap.xml\n" % URL
    open(os.path.join(ROOT, "robots.txt"), "w", encoding="utf-8").write(txt)

def build_manifest():
    manifest = {
        "name": BRAND,
        "short_name": BRAND,
        "start_url": "/",
        "display": "standalone",
        "background_color": "#fbfbfa",
        "theme_color": cfg["themeColor"],
        "description": cfg["description"],
        "icons": [
            {"src": "/assets/icons/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any maskable"},
            {"src": "/assets/icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"}
        ]
    }
    json.dump(manifest, open(os.path.join(ROOT, "manifest.json"), "w", encoding="utf-8"), indent=2)

def build_tool_page(slug, panel_html, script, how_it_works, example, faqs, disclaimer=None, related_override=None, extra_head=""):
    t = tool_by_slug[slug]
    c = cat_by_slug[t["category"]]
    related = related_override or [x for x in tools_by_cat.get(t["category"], []) if x["slug"] != slug][:4]
    if len(related) < 4:
        extra = [x for x in tools if x["slug"] != slug and x not in related]
        related += extra[:4 - len(related)]

    faq_schema = {
        "@context": "https://schema.org", "@type": "FAQPage",
        "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs]
    }
    app_schema = {
        "@context": "https://schema.org", "@type": "SoftwareApplication",
        "name": t["name"], "applicationCategory": "UtilityApplication",
        "operatingSystem": "Any (web browser)",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "INR"},
        "url": "%s/tools/%s.html" % (URL, slug)
    }
    breadcrumb_schema = {
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": URL + "/"},
            {"@type": "ListItem", "position": 2, "name": c["name"], "item": "%s/categories/%s.html" % (URL, c["slug"])},
            {"@type": "ListItem", "position": 3, "name": t["name"], "item": "%s/tools/%s.html" % (URL, slug)},
        ]
    }
    schema = "\n".join('<script type="application/ld+json">%s</script>' % json.dumps(s) for s in [app_schema, faq_schema, breadcrumb_schema])

    disclaimer_html = '<div class="disclaimer">%s</div>' % disclaimer if disclaimer else ""

    body = """
<div class="container" style="padding-top:20px">
  <p class="breadcrumb"><a href="/">Home</a> / <a href="/categories/%s.html">%s</a> / %s</p>
  <div class="tool-header">
    <h1>%s</h1>
    <p class="desc">%s</p>
  </div>

  <div class="tool-panel">
    %s
  </div>
  %s

  <div class="content-block">
    <h2>How it works</h2>
    %s
    <h2>Example</h2>
    %s
    <h2>Frequently asked questions</h2>
    <div class="faq">
      %s
    </div>
  </div>

  <section>
    <div class="section-head"><h2>Related tools</h2></div>
    <div class="grid grid-4">
      %s
    </div>
  </section>
</div>
<script>%s</script>
""" % (
        t["category"], c["name"], t["name"],
        t["name"], t["short"],
        panel_html,
        disclaimer_html,
        how_it_works,
        example,
        "\n".join('<details><summary>%s</summary><p>%s</p></details>' % (q, a) for q, a in faqs),
        "\n".join(tool_card(x) for x in related[:4]),
        script,
    )
    html = page(
        title="%s &mdash; Free Online Tool | %s" % (t["name"], BRAND),
        description=t["short"],
        canonical="%s/tools/%s.html" % (URL, slug),
        body=body,
        body_attrs='data-tool-slug="%s"' % slug,
        schema=schema,
        extra_head=extra_head,
    )
    open(os.path.join(ROOT, "tools", slug + ".html"), "w", encoding="utf-8").write(html)

if __name__ == "__main__":
    build_tools_data_js()
    build_homepage()
    build_all_tools_page()
    build_category_pages()
    build_static_pages()
    build_404()
    build_sitemap()
    build_robots()
    build_manifest()

    import tool_pages_student, tool_pages_finance, tool_pages_calc, tool_pages_everyday, tool_pages_pdf, tool_pages_career_ai
    import tool_pages_pdf_advanced, tool_pages_pdf_advanced2, tool_pages_pdf_office
    tool_pages_student.register()
    tool_pages_finance.register()
    tool_pages_calc.register()
    tool_pages_everyday.register()
    tool_pages_pdf.register()
    tool_pages_career_ai.register()
    tool_pages_pdf_advanced.register()
    tool_pages_pdf_advanced2.register()
    tool_pages_pdf_office.register()
    print("Generated %d tool pages" % len(tools))
    print("Generated: homepage, tools.html, %d category pages, legal pages, 404, sitemap, robots, manifest" % len([c for c in cats if tools_by_cat.get(c["slug"])]))

